
name: Playwright Tests

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main] 

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          

      - name: Install dependencies
        run: |
          cd react frontend
          npm i --force

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: react frontend

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: react frontend
